apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YukDongJin/library-backend.git
    targetRevision: main
    path: .
    directory:
      include: 'k8s-deployment.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true